# Generated by Django 3.2.5 on 2023-03-29 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='Event_Status',
            field=models.CharField(choices=[('Preparing', 'Preparing'), ('Failure', 'Failure'), ('Postponed', 'Postponed'), ('Success', 'Success')], max_length=50),
        ),
    ]
